[package]
edition = "2021"
name = "potion"
version = "0.1.0"

[dependencies]
bevy = "0.8"
bevy_egui = "0.15"
sabi = {path = "../sabi/sabi"}
serde = {version = "1.0", features = ["derive"]}

bevy_fly_camera = {git = "https://github.com/Aceeri/bevy_fly_camera", branch = "bevy-0.8"}
bevy_mod_outline = {git = "https://github.com/komadori/bevy_mod_outline", rev = "4627eaa093e0bc0f292ca19e5af631507840d313"}
bevy_mod_wanderlust = "0.2"

bevy-inspector-egui = "0.12"
bevy-inspector-egui-rapier = {version = "0.5", features = ["rapier3d"]}
bevy_editor_pls = "0.1"
#bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
bevy_framepace = "0.6"
bevy_rapier3d = {version = "0.16", features = ["serde-serialize"]}
bincode = "1.3"
bitflags = "1.3"
derive_more = "0.99"
egui = "0.18"
fixed = {version = "1.11", features = ["serde", "std", "serde-str"]}
fxhash = "0.2"
igd = "0.12"
iyes_loopless = {version = "0.7", features = ["states"]}
lazy_static = "1.4"
leafwing-input-manager = "0.5"
my_internet_ip = "0.1"
num-traits = "0.2"
rand = "0.8"
ron = "0.8"
smallvec = "1.7"
smolset = "1.3"
vec-collections = "0.4"
wgpu-types = "0.13"
zstd = "0.11"

bevy_renet = "0.0.5"
renet_visualizer = "0.0.2"

[[bin]]
name = "local"
path = "src/local.rs"

[[bin]]
name = "server"
path = "src/server.rs"
