[replicate]
"potion::slot::SlotGracePeriod" = 44
"potion::slot::Slot" = 45
"bevy_rapier2d::geometry::collider::Collider" = 3
"bevy_rapier3d::dynamics::rigid_body::RigidBody" = 2
"bevy_rapier3d::dynamics::rigid_body::Velocity" = 27
"bevy_rapier3d::dynamics::rigid_body::Ccd" = 31
"bevy_rapier3d::geometry::collider::CollisionGroups" = 12
"potion::slot::SlotSettings" = 46
"potion::player::Speed" = 19
"bevy_rapier2d::dynamics::rigid_body::Ccd" = 18
"potion::slot::Slottable" = 43
"bevy_transform::components::transform::Transform" = 5
"bevy_rapier3d::dynamics::rigid_body::GravityScale" = 32
"potion::slot::SlotDeposit" = 47
"bevy_rapier2d::dynamics::rigid_body::Damping" = 40
"bevy_rapier3d::geometry::collider::Restitution" = 21
"bevy_rapier2d::dynamics::rigid_body::AdditionalMassProperties" = 25
"bevy_rapier2d::geometry::collider::Sensor" = 26
"bevy_rapier2d::geometry::collider::ColliderMassProperties" = 16
"bevy_rapier2d::geometry::collider::Friction" = 39
"bevy_rapier2d::dynamics::rigid_body::Dominance" = 14
"bevy_rapier2d::dynamics::rigid_body::Sleeping" = 29
"bevy_rapier2d::dynamics::rigid_body::ExternalImpulse" = 11
"bevy_rapier3d::dynamics::rigid_body::ExternalImpulse" = 35
"bevy_rapier3d::dynamics::rigid_body::AdditionalMassProperties" = 22
"bevy_rapier2d::dynamics::rigid_body::GravityScale" = 17
"bevy_rapier2d::geometry::collider::CollisionGroups" = 41
"bevy_transform::components::global_transform::GlobalTransform" = 42
"bevy_rapier2d::geometry::collider::Restitution" = 10
"bevy_rapier3d::geometry::collider::Friction" = 23
"bevy_rapier2d::dynamics::rigid_body::LockedAxes" = 9
"bevy_rapier2d::geometry::collider::ColliderScale" = 8
"bevy_rapier2d::dynamics::rigid_body::Velocity" = 38
"bevy_rapier2d::dynamics::rigid_body::ExternalForce" = 34
"bevy_rapier2d::dynamics::rigid_body::RigidBody" = 4
"bevy_rapier3d::geometry::collider::SolverGroups" = 36
"bevy_rapier3d::dynamics::rigid_body::ExternalForce" = 33
"bevy_rapier3d::geometry::collider::ColliderMassProperties" = 24
"bevy_rapier3d::geometry::collider::Sensor" = 6
"bevy_rapier2d::geometry::collider::SolverGroups" = 37
"bevy_rapier3d::dynamics::rigid_body::LockedAxes" = 7
"bevy_rapier3d::dynamics::rigid_body::Dominance" = 13
"bevy_rapier3d::geometry::collider::ColliderScale" = 15
"bevy_rapier3d::dynamics::rigid_body::Damping" = 30
"bevy_rapier3d::dynamics::rigid_body::Sleeping" = 20
"bevy_core::name::Name" = 28
"bevy_rapier3d::geometry::collider::Collider" = 1

